"""
Pydantic v2 schemas for alerts and officer approval workflow.

AlertOut         — serialised alert record returned by the API
ApprovalRequest  — request body for POST /recommendations/{id}/approve
ApprovalOut      — serialised approval record returned by the API
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class AlertOut(BaseModel):
    """
    Represents a single alert drafted by the co-pilot and stored in the
    ``alerts`` table.

    Status lifecycle: draft → approved → published | rejected
    """

    id: UUID = Field(..., description="Unique alert record identifier")
    recommendation_id: UUID = Field(
        ..., description="FK to the recommendation that produced this alert"
    )
    channel: str = Field(
        ...,
        description="Publication channel: 'vms', 'radio', or 'social'",
    )
    draft_text: str = Field(
        ...,
        description="Draft message text as generated by the co-pilot",
    )
    status: str = Field(
        ...,
        description="Alert lifecycle status: 'draft', 'approved', 'published', 'rejected'",
    )
    created_at: datetime = Field(..., description="Timestamp when the alert record was created")

    model_config = {"from_attributes": True, "populate_by_name": True}


class ApprovalRequest(BaseModel):
    """
    Request body submitted when an officer approves or rejects a recommendation.

    The ``action`` field is not included here because it is expressed via the
    HTTP method / path (e.g. POST .../approve  vs  POST .../reject).  The
    endpoint handler is responsible for setting the action string before
    persisting the approval record.
    """

    officer_id: str = Field(
        ...,
        min_length=1,
        description="Badge number or user ID of the approving / rejecting officer",
    )
    note: str | None = Field(
        default=None,
        max_length=1000,
        description="Optional free-text justification or modification note",
    )
    phone_number: str | None = Field(
        default=None,
        description="If set, send an SMS notification to this number after publishing",
    )

    model_config = {"populate_by_name": True}


class BulkPublishRequest(BaseModel):
    """Request body for POST /alerts/bulk-publish."""

    alert_ids: list[UUID] = Field(
        ..., min_length=1, description="List of alert UUIDs to publish in one operation"
    )
    officer_id: str = Field(..., min_length=1, description="Badge number or user ID of the publishing officer")
    phone_number: str | None = Field(
        default=None,
        description="If set, send a consolidated SMS to this number after all alerts are published",
    )

    model_config = {"populate_by_name": True}


class BulkPublishItemOut(BaseModel):
    """Per-alert result inside a bulk-publish response."""

    alert_id: UUID
    status: str = Field(..., description="'published', 'skipped', or 'error'")
    channel: str | None = None
    message: str | None = None
    detail: str | None = Field(default=None, description="Error or skip reason when status != 'published'")


class BulkPublishOut(BaseModel):
    """Response for POST /alerts/bulk-publish."""

    published_count: int
    skipped_count: int
    error_count: int
    results: list[BulkPublishItemOut]
    sms: dict | None = Field(default=None, description="SMS send result, present when phone_number was supplied")

    model_config = {"populate_by_name": True}


class ApprovalOut(BaseModel):
    """
    Serialised approval record as stored in the ``approvals`` table.

    ``action`` will be one of: 'approved', 'rejected', 'modified'.
    """

    id: UUID = Field(..., description="Unique approval record identifier")
    recommendation_id: UUID = Field(
        ..., description="FK to the recommendation that was acted upon"
    )
    officer_id: str = Field(
        ..., description="Badge number or user ID of the officer who took the action"
    )
    action: Literal["approved", "rejected", "modified"] = Field(
        ..., description="The decision taken by the officer"
    )
    note: str | None = Field(
        default=None,
        description="Optional officer note explaining the decision or requested modification",
    )
    actioned_at: datetime = Field(
        ..., description="Timestamp when the approval / rejection was recorded"
    )

    model_config = {"from_attributes": True, "populate_by_name": True}
